Fixed consistent ux for create Dev environment tab for all entry points in JB
aws/aws-toolkit-jetbrains pull request #3483
Opened 2023-02-15 01:19 UTC by vchikoti1998

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Description
Fixed consistent ux for create Dev environment tab for all entry points in JB

## Checklist
- [ ] My code follows the code style of this project
- [ ] I have added tests to cover my changes
- [ ] A short description of the change has been added to the **[CHANGELOG](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md#contributing-via-pull-requests)** if the change is customer-facing in the IDE.
 
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-15 01:49 UTC, manodnyab commented
Can you attach a screenshot for this PR?

2023-02-15 05:00 UTC, vchikoti1998 commented
> Can you attach a screenshot for this PR?

Updated with screen recording

2023-02-15 20:56 UTC, jparkhurst3 commented
It looks like in the third example (open from next to repo name) the project and repo fields are defaulting to a different set - even though you hit the button from Project "First Proj" and Repo "First Dummy".
They're defaulting correctly in the second example (open from project name) however.

2023-02-16 18:26 UTC, rli requested changes
users should still be able to create workspaces with no associated repository

2023-03-08 01:55 UTC, vchikoti1998 commented on jetbrains-gateway/src/software/aws/toolkits/jetbrains/gateway/CawsConnectorViewPanels.kt
> +    NEW_FROM_EXISTING
The added Enum represents the 2 new radioButtons ```cloneRepo``` and ```create an empty Dev Environment```

2023-03-08 02:03 UTC, vchikoti1998 commented on jetbrains-gateway/src/software/aws/toolkits/jetbrains/gateway/CawsConnectorViewPanels.kt
> +            lateinit var existingBranchRadioButton: Cell<JBRadioButton>
All of them, because these variables are used in different radioButton actions

2023-03-08 02:19 UTC, vchikoti1998 commented on jetbrains-gateway/src/software/aws/toolkits/jetbrains/gateway/CawsConnectorViewPanels.kt
> +                        if (context.cloneType == CawsWizardCloneType.UNLINKED_3P) {
sure

2023-03-08 02:26 UTC, vchikoti1998 commented on jetbrains-gateway/src/software/aws/toolkits/jetbrains/gateway/CawsConnectorViewPanels.kt
> +                        if (context.cloneType == CawsWizardCloneType.CAWS) {
Good catch, removing them

2023-03-08 02:29 UTC, vchikoti1998 commented on jetbrains-gateway/src/software/aws/toolkits/jetbrains/gateway/CawsConnectorViewPanels.kt
> +                        // topGap(TopGap.MEDIUM)
done

2023-03-08 02:39 UTC, vchikoti1998 commented on jetbrains-gateway/src/software/aws/toolkits/jetbrains/gateway/CawsConnectorViewPanels.kt
> +                group(message("caws.workspace.settings.repository"), indent = false) {
Done

2023-03-08 02:39 UTC, vchikoti1998 commented on resources/resources/software/aws/toolkits/resources/MessagesBundle.properties
> +caws.workspace.details.clone_repo=Clone repo
done

2023-03-27 21:19 UTC, vchikoti1998 commented
Closing, will be working on new branch

2023-03-28 16:15 UTC, closed without merging