Update more customer facing texts and doc link
aws/aws-toolkit-jetbrains pull request #4895
Opened 2024-09-18 18:20 UTC by willyyhuang

## Types of changes

- [✅] Bug fix (non-breaking change which fixes an issue)
- [❌] New feature (non-breaking change which adds functionality)

## Description
We observed a couple customer copy papercuts related to /dev

- Updated customer facing text copies in /dev
- Changed documentation link
- Removed a close session messaging when clicking for new task

## Checklist
- [✅] My code follows the code style of this project
- [❌] I have added tests to cover my changes
- [❌] A short description of the change has been added to the **[CHANGELOG](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md#contributing-via-pull-requests)** if the change is customer-facing in the IDE.
- [❌] I have added metrics for my changes (if required)
 
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-09-18 20:18 UTC, osdemah approved these changes
LGTM

2024-09-18 21:57 UTC, neilk-aws requested changes

2024-09-18 21:57 UTC, neilk-aws commented on plugins/amazonq/mynah-ui/src/mynah-ui/ui/tabs/generator.ts
> +What would you like work on?`,
Same comment here. "What would you like _to_ work on?"

2024-09-19 04:54 UTC, neilk-aws approved these changes

2024-09-19 17:38 UTC, merged